### ISSUE TITLE
performance profiling

### ISSUE THREAD

**Issue by yzhaiustc** [pangxie100/HPC-pairwise-distance-optimization#1]
Please consider to profile the performance by setting the tic / toc and count the elapsed time among different intervals. 
1. You may want to know the time cost of different function calls, such as GEMM, NRM2 or so and compute the GFLOPS for reach routine. 
2. You may also want to compute the overall performance of the whole routine. Perf = (Total Computations) / (Total elapsed time) in the unit of GFLOPS, then to tell whether this routine is tending memory-bound or computing-bound before moving to the next step.
3. Before starting the profiling, you'll have to make sure to guarantee the correctness of your code. Otherwise, the performance becomes meaningless.
4. Please let me know if you have any questions.

**Comment by pangxie100** [comment]
1. Time cost of different function calls can be seen by uncommenting "//#define TIME_COUNT 1" in "pw_dist_mkl_func.c" and "pdist_mkl_float_func.c".

2. For double type matrix, the time cost of each part is:
A: 20 x 15000
B: 20 x 20000
C: 15000 x 20000
...
 t-dnrm2_xy : 0.001290 s
t-daxpy_xy : 0.325923 s
t-dgemm : 0.524351 s
t-sqrt : 0.314260 s
t-total : 1.165825 s
potential improvement ratio by fusing: 55.023176 %

3. For double type matrix, the average overall performance:
pw_dist_mkl : Average elapsed time: 1.185069s, Perf: 10.125990 GFLOPS

4. For float type matrix, the time cost of each part is:
A: 20 x 15000
B: 20 x 20000
C: 15000 x 20000
...
t-snrm2_xy : 0.000737 s
t-saxpy_xy : 0.160721 s
t-sgemm : 0.255170 s
t-sqrt : 0.107818 s
t-total : 0.524447 s
potential improvement ratio by fusing: 51.344962 %

5. For float type matrix, the average overall performance:
pdist_mkl_float : Average elapsed time: 0.526565s, Perf: 22.789224 GFLOPS

6. The problem of correctness comes from the malloc function for matrix C. Every matrix should be set to 0 or an initial value after allocating space. Otherwise, the element in the matrix may sometimes not be 0 as default. If we enlarge the size to M = 4, N = 3, K = 5, then the non-zero value may goes to matrix B which use malloc function earlier than matrix C.

7. Computing the GFLOPS for reach routine and telling memory-bound or computing-bound will be done later.

**Comment by yzhaiustc** [comment]
Thank you. Nice profiling!
